# Generated by Django 4.2.11 on 2024-04-03 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('ssn', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)])),
                ('name', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_reference_no', models.UUIDField(default=uuid.uuid4)),
                ('balance', models.FloatField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Paid In Full'), (2, 'In Collection')])),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1_0.consumer')),
            ],
        ),
    ]
