# Generated by Django 4.2.11 on 2024-04-03 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('v1_0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='consumerbalance',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['created'], name='consumer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerbalance',
            index=models.Index(fields=['created'], name='account_created_idx'),
        ),
    ]
